name: Daily Iris Feature Pipeline

on:
  #schedule:
    # At 15 past every hour
    # - cron: '10 * * * *'
    # At 00:00 UTC every day
    #- cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./src/serverless-ml-intro/requirements.txt


    - name: create python file from notebook and run it
      env:
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: |
        python ./src/serverless-ml-intro/notebook_to_python.py ./src/serverless-ml-intro/iris_training_pipeline.ipynb ./src/serverless-ml-intro/iris_training_pipeline.py
        python ./src/serverless-ml-intro/iris_training_pipeline.py
