name: Daily Wine Batch Inference Pipeline

on:
  schedule:
    # At 15 past every hour
    # - cron: '10 * * * *'
    # At 03:00 UTC every day
    - cron: '3 0 * * *'
    # I just wanted to delay it to make sure the features are in before we interfer
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./src/wine/requirements.txt


    - name: Run Wine Batch Inference Pipeline
      env:
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: python ./src/wine/wine-batch-inference-pipeline.py


